- build-docs/action.yml
- build-notebooks/action.yml
- pyiron-config/action.yml
- unit-tests/action.yml
- update-env-files/action.yml
- write-environment/action.yml
> Only go up one level now that actions are in the root

- .github/workflows/pr-labeled.yml
- .github/workflows/push-pull-main.yml
- README.md
> Facilitate non unit tests

- .github/workflows/push-pull-main.yml
- README.md
Uses the notebooks env input variable
> Keep the binder env up to date like the docs env

- .github/workflows/pr-labeled.yml
- .github/workflows/tests-and-coverage.yml
This way it can be called both on label AND on schedule
I closed #16 prematurely, but this does the rest of what's needed.
> Move the full test suite and coverage to their own workflow

- .github/workflows/pr-labeled.yml
I was using actions syntax for the workflows. Also tweaked the labels.
> Fix labeled

- .github/workflows/tests-and-coverage.yml
Must have copied and pasted from `codeql.yml` without updating...
> Correct docstring

- .github/workflows/push-pull-main.yml
I don't want to always wait for the cron job to see the coverage update
> Also run coverage when merging into main.

- .github/workflows/push-pull-main.yml
> Fix dependabot auto action

- .github/workflows/push-pull-main.yml
- .github/workflows/release.yml
- .github/workflows/tests-and-coverage.yml
- build-docs/action.yml
- build-notebooks/action.yml
- cached-mamba/action.yml
- pip-check/action.yml
- unit-tests/action.yml
> Use 3.11 as the "main" version of python

- .support/update_environment.py
- update-env-files/action.yml
Would also solve #55 since I discovered this potential problem while writing this.
> Allow for multiple environment.yml to be updated.

- .github/workflows/push-pull-main.yml
- .github/workflows/tests-and-coverage.yml
The runners are not behaving as reliably as I'd like, and suddenly they are complaining about stringyness...
> Hotfix string parsing issues

- .github/workflows/tests-and-coverage.yml
> Hotfix tests and coverage variables

- .support/condamerge.py
> Revert "Support pip section in condamerge"

- .support/condamerge.py
I sneakily force reset main to its pre #78 state to avoid the revert commits.
> Correct #78

- .support/condamerge.py
@liamhuber This should fix the empty pip issue.
> Do not write pip section if not needed

- .support/update_environment.py
I've checked it locally on a dependabot PR on repos with and without pip deps, so I hope this should just work.  I had to add some logic in case the bumped packages is a pip dependency.  In this case it's not necessary to change the name. That part I couldn't test, because we don't have a that case in PR right now.
> Update env updater for pip sections

- .support/update_actions_tag.sh
Default value is the name of the branch that we're on.
Per comment in #65
> Add a helper script for internally updating the action tags

- .support/update_actions_tag.sh
I was only updating the tag on _one_ action 🤦‍♂️
> :bug: Hotfix tag updater

- .github/workflows/dependabot-pr.yml
- .github/workflows/pr-labeled.yml
- .github/workflows/push-pull.yml
- .github/workflows/tests-and-coverage.yml
- README.md
- build-docs/action.yml
- build-notebooks/action.yml
- cached-mamba/action.yml
- pip-check/action.yml
- unit-tests/action.yml
Yeah, so this isn't a perfect system.
> [patch] :fire: :bug: Re-target main

- .github/workflows/dependabot-pr.yml
- .github/workflows/pr-labeled.yml
- .github/workflows/push-pull.yml
- .github/workflows/tests-and-coverage.yml
- README.md
- build-docs/action.yml
- build-notebooks/action.yml
- cached-mamba/action.yml
- pip-check/action.yml
- unit-tests/action.yml
Defaults to no env files, in which case it won't run. Useful for, e.g., running an env of lower bounds.
> [patch] Add another set of tests for a different env

- .github/workflows/pyproject-release.yml
Did this not get committed? I swear I already fixed this
> No .yml at the end of action call

- .github/workflows/dependabot-pr.yml
- .github/workflows/pr-labeled.yml
- .github/workflows/push-pull.yml
- .github/workflows/pyproject-release.yml
- .github/workflows/tests-and-coverage.yml
- README.md
- build-docs/action.yml
- build-notebooks/action.yml
- cached-mamba/action.yml
- cached-miniforge/action.yml
- pip-check/action.yml
- unit-tests/action.yml
To streamline the reusable workflows.
This removes a bunch of input variables (which are now automated 🎉) so the public signatures are changing this is a major bump
> [major] Use cached miniforge

- .github/workflows/dependabot-pr.yml
- .github/workflows/pr-labeled.yml
- .github/workflows/push-pull.yml
- .github/workflows/pyproject-release.yml
- .github/workflows/release.yml
- .github/workflows/tests-and-coverage.yml
- README.md
- build-docs/action.yml
- build-notebooks/action.yml
- cached-miniforge/action.yml
- pip-check/action.yml
- unit-tests/action.yml
> [minor] Bump python

- .github/workflows/pyproject-release.yml
Useful for debugging new build recipes
> [patch] A convenience flag for disabling the actual publishing step

- .github/workflows/pr-target-opened.yml
Just a minor syntax adjustment.
Per the github-actions breaking changes log: https://github.com/actions/github-script/tree/main?tab=readme-ov-file#v5
> [patch] :fire: :bug: Binder button fix

- .github/workflows/push-pull.yml
Based on https://github.com/pyiron/pyiron_workflow/pull/520
> [patch] Add ruff to the push-pull job (default off)

- .support/pypi_vs_conda_names.json
@pmrv such a change might be needed also elsewhere.
> Add landau to pypi_vs_conda_names.json

- .github/workflows/dependabot-pr.yml
- .github/workflows/pr-labeled.yml
- .github/workflows/push-pull.yml
- .github/workflows/pyproject-release.yml
- .github/workflows/tests-and-coverage.yml
- README.md
- build-docs/action.yml
- build-notebooks/action.yml
- cached-miniforge/action.yml
- pip-check/action.yml
- unit-tests/action.yml
Rely on local repositories for configuration. The job flag defaults to false, so this is job is backwards-compatible.
> Add an optional mypy job

- .github/workflows/dependabot-pr.yml
- .github/workflows/hatch-release.yml
- .github/workflows/pr-labeled.yml
- .github/workflows/push-pull.yml
- .github/workflows/pyproject-release.yml
- .github/workflows/tests-and-coverage.yml
- README.md
- build-docs/action.yml
- build-notebooks/action.yml
- cached-miniforge/action.yml
- pip-check/action.yml
- unit-tests/action.yml
Add a workflow for releasing with hatch
> Actions 4.0.6
