.github/workflows/release.yml
Without specifying the release type, release CI gets invoked three times.
=> Better hint for release CI

.github/workflows/push-pull-main.yml
I ran into trouble over on ironflow at this step `Running on Github Actions but GITHUB_TOKEN is not set. Add "env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}" to your step config.`, and sure enough [their docs explicitly pass the token to the env](https://github.com/TheKevJames/coveralls-python/blob/master/docs/usage/configuration.rst#github-actions-support)
=> Explicitly add the token to the env

.github/workflows/pr-labeled.yml, .github/workflows/push-pull-main.yml
Changes the "integration" label to "tests", and uses it to run integration, benchmark, and unit tests, and then runs coverage and codacy on the result. Coverage and codacy are meanwhile completely removed from the on-push-pull workflows.
This way coverage and codacy will see *all* the tests, and main won't get a red X if coverage drops (since we won't run on push).
Pending the merge of #15 (which this branched off of) and any revelations in #16.
=> Rearrange tests

.github/workflows/tests-and-coverage.yml
Over in ironflow I get the following error, maybe because there is now two layers of workflows? `ERROR - environment variable CODACY_PROJECT_TOKEN is not defined.`
=> Add token value to env

.github/workflows/tests-and-coverage.yml
[per the docs](https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support) the service name can be "picky". Since the `github-actions` service explicitly requires the `COVERALLS_REPO_TOKEN ` token, and my daily workflow error messages contain `set the COVERALLS_REPO_TOKEN env var.`, I think that's a good hint that the service is not being parsed correctly.
At worst, this is just redundant and we can roll it back.
=> Be more explicit about the service name

.support/build_notebooks.sh
In the `build_notebooks.sh` invocation of papermill. This is a holdover from when we supported python 2.7. The variable isn't even set in the script any more.
=> Remove kernel specification

.github/workflows/tests-and-coverage.yml
I continue to get token validation issues with the daily workflow, despite following the docs (which have a disclaimer that things might not work perfectly for me), so let's just do it the way base and atomistics do it because things are working fine there.
=> Use the same setup as base and atomistics for coveralls

.support/update_environment.py
In recent pyiron_contrib dependabot PRs (e.g. https://github.com/pyiron/pyiron_contrib/pull/696), the number of arguments was wrong (different issue) and the action failed (as intended). However, not with the nice massage we intended (see below). This hopefully fixes this.
```
Run pyiron/actions/update-env-files@main
with:
conda-yml: .ci_support/environment.yml
Run pip install pyyaml
pip install pyyaml
shell: /usr/bin/bash -l {0}
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyyaml in /usr/lib/python[3](https://github.com/pyiron/pyiron_contrib/actions/runs/5111616226/jobs/9188774199#step:3:3)/dist-packages (5.[4](https://github.com/pyiron/pyiron_contrib/actions/runs/5111616226/jobs/9188774199#step:3:5).1)
Run python …
```
=> Fail as intended for to short lists

update-env-files/action.yml
We declare `conda-yml` but try to use `conda-env`. This is what was giving the length errors that led to the cleanup in #42. This should now fix the underlying issue so we don't see that cleaner error 😉
=> Sync input variable used with input variable declared

.github/workflows/push-pull-main.yml
The latest version of numpy (1.25) dropped 3.8 support. Let's also ditch it and add 3.11 to the tests.
=> Replace python 3.8 in unit tests matrix with python 3.11

.support/build_notebooks.sh, README.md
Previously workflow doesn't run notebooks in sub directories, like
root/notebooks/foo/bar.ipynb
Using the `**` notation fixes this.  `EXCLUSION_FILE` should still work, but I haven't checked.
=> Use globstar to run notebooks in subdirs

cached-mamba/action.yml
According to my (limited) experience in pyiron/docker-stack it should be possible to add the date to the `env` of the respective step itself.
=> Refactor env declaration for caching mamba

.support/update_environment.py
I think we just had an off-by-one error when touching up the script.
Closes #61
=> Patch expected lengths

.github/workflows/push-pull-main.yml, .github/workflows/tests-and-coverage.yml, README.md, add-to-python-path/action.yml
To use `pympipool` in other repos [e.g. `pyiron_workflow](https://github.com/pyiron/pyiron_workflow/pull/77), we either need to invoke unit tests from the directory the test files live in, or expand the python path to include those files (cf. [this issue](https://github.com/pyiron/pympipool/issues/239) and [this PR with examples](https://github.com/pyiron/pympipool/pull/238)). Unfortunately, github [does not make it easy to pass env variables to reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations). So, instead, here I'm introducing a new action for easily adding local directories (i.e. prepending the full runner path to the local repo paths provided) to the python path. It needs to be invoked _every job_ since the env is not shared between …
=> Expanding the python path

.github/workflows/push-pull-main.yml, .github/workflows/tests-and-coverage.yml
I'm being pretty bold with the syntax here, so we'll see if it works.
The idea is to let the reusable workflow caller specify which versions of the OS and python they want to use. This becomes important for packages relying on `pympipool`, since OSX >11 is not playing nicely with MPI right now.
EDIT:
Ok, it's all working when tested over in [`pyiron_workflow`](https://github.com/pyiron/pyiron_workflow/pull/108).
This PR exposes python version and runners as optional input to two of the reusable workflows, and reformulates the unit test matrix to use them. In particular, we now have a primary runner and python version, and two alternate versions of each. By default this is just the standard (ubuntu-latest, 3.11), and (windows-latest, macos-latest) and (3.10 and 3.9). Without any input from …
=> Expose OS and py versions as input on reusable workflows

.github/workflows/tests-and-coverage.yml
I was lazy on the last PR and didn't test the nested reusable workflow because that's really a pain. It had copypasta problems. Take-home messages are (a) haste makes errors, and (b) nesting the reusable workflows is a huge pain in the ass
=> Use inputs not matrix

cached-mamba/action.yml
> I am still not familiar enough to guarantee that the syntax you're using will work, but I am definitely a fan of the change as it (slightly) simplifies the action file.
Yes, I am also not 100% sure, only quite sure 😅 However, in the worst case, the caching is not properly working and we can revert this change :D 
I will try to keep an eye open on any hiccups, however, you will probably experience such before I do. If there is something not working as intended, just revert :)
_Originally posted by @niklassiemer in https://github.com/pyiron/actions/issues/57#issuecomment-1803295251_
We have the feared hiccups, thus, 
Reverts pyiron/actions#57
Closes #73
=> Revert "Refactor env declaration for caching mamba"

.support/environment-docs.yml, write-docs-env/action.yaml
This includes `myst-parser` (along with the existing `ipykernel` and `nbsphinx`) into the environment for all invocations of the `build-docs` action unless the [`standard-docs-env-file`](https://github.com/pyiron/actions/blob/7b7eff54a5c35f63e4d5f2782cc766e31be2580d/build-docs/action.yml#L18) is overridden at call time.
Pros: This package is necessary for parsing `.md` files in the sphinx docs, and so is super useful when the `README.md` lives in `docs/` and gets used for the readthedocs landing page -- as I've already done for `pyiron_workflow` and am now doing [in this PR](https://github.com/pyiron/pyiron_module_template/pull/20) for `pyiron_module_template`.
Cons: bloats the docs env in case someone _doesn't_ need `myst-parser`. @jan-janssen, I see you have it in `pyiron/atomistics` as …
=> Include myst-parser, sphinx-gallery, and the rtd theme in the base docs environment

.support/condamerge.py
When adding a section for pip packages this adds a dictionary to the output of the yaml parser, which tripped the rest of the script up.
=> Support pip section in condamerge

.support/pypi_vs_conda_names.json
This fixes the issue I mentioned at the end of the pyiron meeting.  Just a matter of the pypi/conda names not lining up.
=> Add h5io browser to pypi conda mapping

.github/workflows/dependabot-pr.yml, .github/workflows/pr-labeled.yml, .github/workflows/push-pull.yml, .github/workflows/tests-and-coverage.yml, .support/environment-docs.yml, README.md, build-docs/action.yml, build-notebooks/action.yml, cached-mamba/action.yml, pip-check/action.yml, unit-tests/action.yml
When I switched over to pyproject.toml and got rid of the local `versioneer.py` file in https://github.com/pyiron/pyiron_ontology/pull/51, the docs failed to build because `conf.py` couldn't run `versioneer.get_version()` anymore. This fixed that.
=> [patch] Add versioneer dependency

.support/pypi_vs_conda_names.json
In the pyproject version releaser, I guess it will be possible to try with a `.replace("-", "_")` since pip in general uses "-" in place of "_". However, we can't just uniformly do that in the environment updater as there are legit conda packages that will allow "-". For now, I just extend the whitelist of (pyiron) packages where we know the conda version is "_"
=> [patch] Extend pypi2conda map

update-pyproject-dependencies/action.yml
By default, free the patch version on semantically versioned dependencies in `update-pyproject-dependencies`. Unstable (0.Y.Z) projects still get pinned to the patch by default.
This would be a breaking change if there were users depending on this default, but there most certainly are not so minor is sufficient.
=> [minor] change default semantic upper limit

.github/workflows/dependabot-pr.yml, .github/workflows/pr-labeled.yml, .github/workflows/push-pull.yml, .github/workflows/pyproject-release.yml, .github/workflows/tests-and-coverage.yml, README.md, build-docs/action.yml, build-notebooks/action.yml, cached-miniforge/action.yml, pip-check/action.yml, unit-tests/action.yml
So you can target something other than the tests directory; necessary when the tests are found recursively and you want to add sub-folders to the path.
Changes the workflow interface, so major.
=> [major] Change python path input from a bool to a variable

cached-miniforge/action.yml, write-environment/action.yml
Per #123, non-default (3.12) python version unit tests are not being run. Let's fix this.
=> [patch] Debug py version

.github/workflows/dependabot-pr.yml, .github/workflows/pr-labeled.yml, .github/workflows/push-pull.yml, .github/workflows/pyproject-release.yml, .github/workflows/tests-and-coverage.yml, README.md, build-docs/action.yml, build-notebooks/action.yml, cached-miniforge/action.yml, pip-check/action.yml, unit-tests/action.yml
Changing default value for  options that passes `cached-miniforge` to `conda-incubator/setup-miniconda` to deal with the sunsetting of Mambaforge: https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/
=> Forge variant

.github/workflows/dependabot-pr.yml, .github/workflows/pr-labeled.yml, .github/workflows/push-pull.yml, .github/workflows/pyproject-release.yml, .github/workflows/tests-and-coverage.yml, README.md, build-docs/action.yml, build-notebooks/action.yml, cached-miniforge/action.yml, pip-check/action.yml, unit-tests/action.yml
Ok, so there was an issue with actions still referencing `...@forge variant` (see #132). I guess `.support/update_actions_tag.sh` wasn't run before merging into main.
I now ran the script directly on branch `v3.3.2`. I think this resolves the issue. However, this need to be merged into main as well. I'm not sure if this is re right way to do such thing, so could you have a look, @liamhuber ?
=> run update_actions_tag.sh

.github/workflows/codeql.yml, .github/workflows/dependabot-pr.yml, .github/workflows/pr-labeled.yml, .github/workflows/pr-target-opened.yml, .github/workflows/push-pull.yml, .github/workflows/pyproject-release.yml, .github/workflows/release.yml, .github/workflows/tests-and-coverage.yml
I pick up [this one](https://github.com/pyiron/actions/pull/134)
=> [Patch] Set the default runner to `ubuntu-22.04` and expose it as input everywhere

.github/workflows/push-pull.yml
Honestly, I don't remember for sure whether the custom workflows in `.github/` were part of the API or not, but having this default on would cause a bunch of repos to start failing if they target it, so for now I'm flagging it "major".
=> [major] Make the ruff checks happen by default

.github/workflows/push-pull.yml
Formatting the whole repository should be the default. Exclusion of files and directories should be the exception. Not the other way round. Files and directories can be excluded via `pyproject.toml`:
```
[tool.black]
extend-exclude = ''' 
(
^/docs
)
'''
=> [major] run black on the whole repository

.github/workflows/push-pull.yml, .github/workflows/tests-and-coverage.yml
With ruff and black across the whole repo (excl. docs) by default in the next actions release, I don't see a need to keep running codacy. From what I understand it may be useful if we want to apply additional screenings for things like cryptographic or license compliance, but we're not really leveraging any of that afaik. I'm happy to keep the functionality available, but I'm inclined to make it on-request instead of always there.
Thoughts?
=> [minor] Change codacy to default off

.github/workflows/dependabot-pr.yml, .github/workflows/pr-labeled.yml, .github/workflows/push-pull.yml, .github/workflows/pyproject-release.yml, .github/workflows/tests-and-coverage.yml, .support/update_actions_tag.sh, README.md, build-docs/action.yml, build-notebooks/action.yml, cached-miniforge/action.yml, pip-check/action.yml, unit-tests/action.yml
As of five days ago, are getting [CI issues](https://github.com/pyiron/pyiron_workflow/issues/634). The mamba example on setup-miniconda stopped working too. I can't find or figure out a good direct attack, but mamba is deprecated anyhow so let's see whether it's possible to simply get around the problem by modernizing our setup-miniconda usage.
- Using mamba is deprecated, don't bother
- Localize env names containing paths with a `./` -- partially fixes https://github.com/pyiron/pyiron_workflow/issues/634
- Remove the backwards compatible env name input (since removing the mamba flags breaks the interface anyhow)
- Sneaky unrelated: patch the `sed` invocation for osx
It's been just about a year since v3 dropped, so instead of deprecating the `use_mamba` flag, let's just get rid of it, …
=> [major] Updates to cached-miniforge

.github/workflows/dependabot-pr.yml, .github/workflows/pr-labeled.yml, .github/workflows/push-pull.yml, .github/workflows/pyproject-release.yml, .github/workflows/tests-and-coverage.yml, README.md, build-docs/action.yml, build-notebooks/action.yml, cached-miniforge/action.yml, pip-check/action.yml, unit-tests/action.yml
To times when we're actually trying to get the coverage.
#146 left the codacy and coveralls env as part of the `unit-test` action environment, which is correct in terms of backwards compatibility, but in the actual reusable workflows we can and want to turn it off whenever we're not actually trying to run coverage.
=> [patch] Limit coverage env

.github/workflows/dependabot-pr.yml, .github/workflows/pr-labeled.yml, .github/workflows/push-pull.yml, .github/workflows/pyproject-release.yml, .github/workflows/tests-and-coverage.yml, README.md, build-docs/action.yml, build-notebooks/action.yml, cached-miniforge/action.yml, pip-check/action.yml, unit-tests/action.yml
Leveraging python path additions more uniformly in the jobs where we actually run stuff, and sending the input python version to the python setup for linter jobs
=> More python control

.github/workflows/dependabot-pr.yml, .github/workflows/hatch-release.yml, .github/workflows/pr-labeled.yml, .github/workflows/push-pull.yml, .github/workflows/pyproject-release.yml, .github/workflows/tests-and-coverage.yml, README.md, build-docs/action.yml, build-notebooks/action.yml, cached-miniforge/action.yml, pip-check/action.yml, unit-tests/action.yml
In the unit-test action, and propagate the docstring change up through the tools that depend on this. This gives finer-grained control for which tests to run where (in particular, to exclude the benchmark tests from the coverage run, if you want)
=> Allow multiple test directories
